source/Dockerfile: Build Kong from source
The source/ directory builds Kong from source using OpenResty
1.15.8.1 (rc1) and attempts to work as a drop-in replacement for
alpine/ and centos/ containers for use with compose/.

Currently the OpenResty build is failing, possibly due to an
incompatible patch:

    cc -c -I/openresty-1.15.8.1rc1/build/luajit-root/usr/local/opt/openresty-1.15.8.1rc1-kong/luajit/include/luajit-2.1 -I/openresty-1.15.8.1rc1/build/luajit-root/usr/local/opt/openresty-1.15.8.1rc1-kong/luajit/include/luajit-2.1  -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -g -O2 -I/usr/local/opt/include -DNDK_SET_VAR -DNDK_UPSTREAM_LIST -DNDK_SET_VAR -DNDK_SET_VAR -DNDK_SET_VAR -DLUA_DEFAULT_PATH='"/usr/local/opt/openresty-1.15.8.1rc1-kong/site/lualib/?.ljbc;/usr/local/opt/openresty-1.15.8.1rc1-kong/site/lualib/?/init.ljbc;/usr/local/opt/openresty-1.15.8.1rc1-kong/lualib/?.ljbc;/usr/local/opt/openresty-1.15.8.1rc1-kong/lualib/?/init.ljbc;/usr/local/opt/openresty-1.15.8.1rc1-kong/site/lualib/?.lua;/usr/local/opt/openresty-1.15.8.1rc1-kong/site/lualib/?/init.lua;/usr/local/opt/openresty-1.15.8.1rc1-kong/lualib/?.lua;/usr/local/opt/openresty-1.15.8.1rc1-kong/lualib/?/init.lua"' -DLUA_DEFAULT_CPATH='"/usr/local/opt/openresty-1.15.8.1rc1-kong/site/lualib/?.so;/usr/local/opt/openresty-1.15.8.1rc1-kong/lualib/?.so"' -DNDK_SET_VAR -I src/core -I src/event -I src/event/modules -I src/os/unix -I ../ngx_devel_kit-0.3.1rc1/objs -I objs/addon/ndk -I ../ngx_lua-0.10.14/src/api -I /openresty-1.15.8.1rc1/build/luajit-root/usr/local/opt/openresty-1.15.8.1rc1-kong/luajit/include/luajit-2.1 -I ../ngx_stream_lua-0.0.6/src/api -I objs \
	    -o objs/src/event/ngx_event_openssl_stapling.o \
	    src/event/ngx_event_openssl_stapling.c
    src/event/ngx_event_openssl.c: In function 'bio_read':
    src/event/ngx_event_openssl.c:255:11: warning: implicit declaration of function 'BIO_get_data' [-Wimplicit-function-declaration]
	 buf = BIO_get_data(bio);
	       ^
    src/event/ngx_event_openssl.c:255:9: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
	 buf = BIO_get_data(bio);
	     ^
    src/event/ngx_event_openssl.c: At top level:
    src/event/ngx_event_openssl.c:287:5: error: 'nullf_write' undeclared here (not in a function)
	 nullf_write,
	 ^
    src/event/ngx_event_openssl.c:289:5: error: 'nullf_puts' undeclared here (not in a function)
	 nullf_puts,
	 ^
    src/event/ngx_event_openssl.c:290:5: error: 'nullf_gets' undeclared here (not in a function)
	 nullf_gets,
	 ^
    src/event/ngx_event_openssl.c:291:5: error: 'nullf_ctrl' undeclared here (not in a function)
	 nullf_ctrl,
	 ^
    src/event/ngx_event_openssl.c:292:5: error: 'nullf_new' undeclared here (not in a function)
	 nullf_new,
	 ^
    src/event/ngx_event_openssl.c:293:5: error: 'nullf_free' undeclared here (not in a function)
	 nullf_free,
	 ^
    src/event/ngx_event_openssl.c:294:5: error: 'nullf_callback_ctrl' undeclared here (not in a function)
	 nullf_callback_ctrl,
	 ^
    src/event/ngx_event_openssl.c:295:1: warning: missing initializer for field 'bputs' of 'BIO_METHOD {aka struct bio_method_st}' [-Wmissing-field-initializers]
     };
     ^
    In file included from /usr/include/openssl/ssl.h:152:0,
		     from src/event/ngx_event_openssl.h:15,
		     from src/core/ngx_core.h:83,
		     from src/event/ngx_event_openssl.c:9:
    /usr/include/openssl/bio.h:317:11: note: 'bputs' declared here
	 int (*bputs) (BIO *, const char *);
	       ^
    src/event/ngx_event_openssl.c: In function 'ngx_ssl_create_connection':
    src/event/ngx_event_openssl.c:1403:13: warning: implicit declaration of function 'BIO_set_data' [-Wimplicit-function-declaration]
		 BIO_set_data(bio, c->buffer);
		 ^
    src/event/ngx_event_openssl.c:1407:13: warning: implicit declaration of function 'BIO_up_ref' [-Wimplicit-function-declaration]
		 BIO_up_ref(oldbio);
		 ^
    src/event/ngx_event_openssl.c:1408:13: warning: implicit declaration of function 'SSL_set0_rbio' [-Wimplicit-function-declaration]
		 SSL_set0_rbio(sc->connection, BIO_push(bio, oldbio));
		 ^
    objs/Makefile:1290: recipe for target 'objs/src/event/ngx_event_openssl.o' failed
    make[2]: *** [objs/src/event/ngx_event_openssl.o] Error 1